apiVersion: v1
kind: ConfigMap
metadata:
  name: db-connector-config
  namespace: chatdb-services
data:
  SPRING_PROFILES_ACTIVE: "kubernetes"
  SERVER_PORT: "8081"
  # Add database connection configurations as needed
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-connector
  namespace: chatdb-services
  labels:
    app: db-connector
    component: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: db-connector
  template:
    metadata:
      labels:
        app: db-connector
        version: v1
    spec:
      containers:
      - name: db-connector
        image: chatdb/db-connector:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8081
          name: http
        envFrom:
        - configMapRef:
            name: db-connector-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 60
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /actuator/health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: db-connector
  namespace: chatdb-services
  labels:
    app: db-connector
spec:
  selector:
    app: db-connector
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: http
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: db-connector-hpa
  namespace: chatdb-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-connector
  minReplicas: 2
  maxReplicas: 8
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80