apiVersion: v1
kind: ConfigMap
metadata:
  name: prediction-service-config
  namespace: chatdb-services
data:
  MODEL_REGISTRY_URL: "http://model-registry.chatdb-services.svc.cluster.local:8080"
  CACHE_TTL: "3600"
  MAX_CACHE_SIZE: "100"
  METRICS_PORT: "9090"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prediction-service
  namespace: chatdb-services
  labels:
    app: prediction-service
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prediction-service
  template:
    metadata:
      labels:
        app: prediction-service
        version: v1
    spec:
      containers:
      - name: prediction-service
        image: chatdb/prediction-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 9090
          name: metrics
        envFrom:
        - configMapRef:
            name: prediction-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: prediction-service
  namespace: chatdb-services
  labels:
    app: prediction-service
spec:
  selector:
    app: prediction-service
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 9090
    targetPort: 9090
    protocol: TCP
    name: metrics
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: prediction-service-hpa
  namespace: chatdb-services
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: prediction-service
  minReplicas: 3
  maxReplicas: 15
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 65
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 75